# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.1.1'

gem 'coderay', '~> 1.1', '>= 1.1.3'
gem 'rack-test', '~> 1.1'
gem 'rspec', '~> 3.11'
gem 'rubocop', '~> 1.26'
gem 'sinatra', '~> 2.2'
